# Generated by Django 3.1.7 on 2021-05-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('N50', 'Nifty 50 listed company'), ('DIV', 'Good dividend yielding company')], default='N50', max_length=3),
        ),
    ]
