# Generated by Django 3.1.7 on 2021-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210508_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bse_code',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
